{% set name = "ipyevents" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1168bd473f19e8394f4fb403ef826a4851eceea4d90f6b3339fc88f28b69be3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - nodejs
    - python >=3
    - pip
  run:
    - python >=3
    - ipywidgets >=7.2.0

test:
  requires:
    - jupyter
    - notebook
  imports:
    - ipyevents
  commands:
    - jupyter nbextension install --sys-prefix --py ipyevents

about:
  home: https://github.com/mwcraig/ipyevents
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A custom widget for returning mouse and keyboard events to Python
  description: A custom widget for returning mouse and keyboard events to Python
  dev_url: https://github/com/mwcraig/ipyevents

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog-conda-forge
