{% set name = "ipyevents" %}
{% set version = "0.6.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0b347229a52978ef8a632b1338317822e437d0d3b03618281462a7a9686d6321" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - nodejs
    - python >=3
    - pip
  run:
    - python >=3
    - ipywidgets >=7.2.0

test:
  requires:
    - jupyter
    - notebook
  imports:
    - ipyevents
  commands:
    - jupyter nbextension install --sys-prefix --py ipyevents

about:
  home: https://github.com/mwcraig/ipyevents
  license: BSD 3-clause
  license_family: BSD
  license_file: 'LICENSE.md'
  summary: A custom widget for returning mouse and keyboard events to Python
  description: A custom widget for returning mouse and keyboard events to Python
  dev_url: 'https://github/com/mwcraig/ipyevents'

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog-conda-forge
