{% set name = "ipyevents" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4cb6d60bd89b54728bb9be92875b9336a3481138f9c552cdaa98eeeefcabf33

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - nodejs =14
    - python >=3.7
    - pip
    - jupyter-packaging
  run:
    - python >=3.7
    - ipywidgets >=7.6

test:
  requires:
    - jupyter
    - notebook
  imports:
    - ipyevents
  commands:
    - jupyter nbextension install --sys-prefix --py ipyevents

about:
  home: https://github.com/mwcraig/ipyevents
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A custom widget for returning mouse and keyboard events to Python
  description: A custom widget for returning mouse and keyboard events to Python
  dev_url: https://github/com/mwcraig/ipyevents

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog-conda-forge
