{% set name = "ipyevents" %}
{% set version = "0.2.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "92bc980832033cc160ceea66cd475d69f28687cc78dbfa0de5e4e7bf0af97930" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - python >=3.3
    - setuptools
  run:
    - python
    - python >=3.3
    - ipywidgets >=7.0.0

test:
  imports:
    - ipyevents

about:
  home: https://github.com/mwcraig/ipyevents
  license: BSD 3-clause
  license_family: BSD
  license_file: 'LICENSE.md'
  summary: A custom widget for returning mouse and keyboard events to Python
  description: A custom widget for returning mouse and keyboard events to Python
  dev_url: 'https://github/com/mwcraig/ipyevents'

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog-conda-forge
