appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VGSFoW7NARvB5cH1xrYR/9+IFjqHpdZwdhJp5Q1jMs/8Gk9gEvv7pErf7hOFfEAB3lCovLkap/0QXlLYFkCB4tcdEzA1jD0ct76Yxp3VFDqmI4ZuaqhrsrftD0ZLoJwcsHFlQJXkqUybBUGp6uA44qlI/YjXPn93Y9U5lmnoereO0B4I4Hu4jYn2mzDMnB9l8leRyWAZmwYhfbXwC9DSgEEzxjYWduA12P8uAmXtZ8nwKdsdL/pRr+xt3MbJEvcODyDnLILFeM5fKYd/ub/qvFniaAo7HYdym1/BohuNkF806+WDeei//5ZotqLS848wEWrUWXsafq2lD7DJ9M9V7kzTpZbARdgh+JV2mRqI3a+grqpefxqM+iDXZZZBqK2jF7HyQJ9SHihqlcMZbc/DPhrUPNg4nYfywzq/M3hl7P5N3YYfjNW8COW71lWWzkrW01Aas+RzHuqrjulh37hju4rVCNwIop8K6e3K+1fpxBZSsuhR+BQr9WuV/EREmzDSddRoo1ZTOZc2DUnV9yJz9981TYTM7zoQOk32XYQK7njivGAh0dWs6M2rijj4Qm14RezfXZcbyImpGbgHpnFzAaPcM/1wHI/LgjrSKmMJw9LsTwavw8niz0Z2x1lvrQ6NVkzANL5LBK4k5+kpRHUutb69g47ZbHWcnQ3OsCW+xKk=}
provider:
  win: azure
